In [1]:
import seaborn as sns
df = sns.load_dataset('titanic')
import numpy as np
import pandas as pd

In [2]:
DF = df.to_csv('titanic.csv',index = False)

In [3]:
df.sample(4)

survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
814         0       3  male  30.5      0      0   8.0500        S   Third   
242         0       2  male  29.0      0      0  10.5000        S  Second   
771         0       3  male  48.0      0      0   7.8542        S   Third   
398         0       2  male  23.0      0      0  10.5000        S  Second   

     who  adult_male deck  embark_town alive  alone  
814  man        True  NaN  Southampton    no   True  
242  man        True  NaN  Southampton    no   True  
771  man        True  NaN  Southampton    no   True  
398  man        True  NaN  Southampton    no   True

In [4]:
df=df[['sex','embarked','alone','pclass','survived']]
df.head()

sex embarked  alone  pclass  survived
0    male        S  False       3         0
1  female        C  False       1         1
2  female        S   True       3         1
3  female        S  False       1         1
4    male        S   True       3         0

In [5]:
df['sex']=np.where(df['sex']=="male",1,0)
df.head()

sex embarked  alone  pclass  survived
0    1        S  False       3         0
1    0        C  False       1         1
2    0        S   True       3         1
3    0        S  False       1         1
4    1        S   True       3         0

In [6]:
#Let's perform label encoding on sex column
import numpy as np
#let's perorm label encoding on embarked
ordinal_label = {k:i for i,k in enumerate(df['embarked'].unique(),0)}
df['embarked'] = df['embarked'].map(ordinal_label)

In [7]:
df.sample(10)

sex  embarked  alone  pclass  survived
775    1         0   True       3         0
623    1         0   True       3         0
310    0         1   True       1         1
286    1         0   True       3         1
779    0         0  False       1         1
415    0         0   True       3         0
833    1         0   True       3         0
183    1         0  False       2         1
182    1         0  False       3         0
852    0         1  False       3         0

In [8]:
#let's perform label encoding on alone
df['alone'] = np.where(df['alone']==True,1,0)

In [9]:
df.head()

sex  embarked  alone  pclass  survived
0    1         0      0       3         0
1    0         1      0       1         1
2    0         0      1       3         1
3    0         0      0       1         1
4    1         0      1       3         0

In [10]:
X = df[['sex','embarked','alone','pclass']]
y = df['survived']

In [17]:
#train test split in usually done to avoid overfitting
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=100) 

In [18]:
X_train.head()
# y_train.head()

sex  embarked  alone  pclass
69     1         0      0       3
85     0         0      0       3
794    1         0      1       3
161    0         0      1       2
815    1         0      1       1

In [19]:
X_train['sex'].unique()

array([1, 0])

In [20]:
X_train.isnull().sum()

sex         0
embarked    0
alone       0
pclass      0
dtype: int64

In [21]:
#perform chi2 test
#chi2 return 2 values
#fscore and the pvalue
from sklearn.feature_selection import chi2
f_p_values=chi2(X_train,y_train)


In [22]:
f_p_values

(array([65.67929505,  7.55053653, 10.88471585, 21.97994154]),
 array([5.30603805e-16, 5.99922095e-03, 9.69610546e-04, 2.75514881e-06]))

In [23]:
import pandas as pd
p_values = pd.Series(f_p_values[1])
p_values.index = X_train.columns
p_values

sex         5.306038e-16
embarked    5.999221e-03
alone       9.696105e-04
pclass      2.755149e-06
dtype: float64

In [24]:
p_values.sort_index(ascending=False)

sex         5.306038e-16
pclass      2.755149e-06
embarked    5.999221e-03
alone       9.696105e-04
dtype: float64